#!/usr/bin/env bash
# Guided (or non-interactive) production configuration.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/_lib.sh"

release_banner
heading "ACTION: Configure"
load_version
audit "configure start"

EXAMPLE="${CONFIG_DIR}/deployment-values.example"
VALUES_FILE="${CONFIG_DIR}/deployment-values.env"
mkdir -p "${CONFIG_DIR}"

prompt_val() {
  local var="$1" label="$2" default="${3:-}" secret="${4:-0}"
  local cur=""
  if [[ -n "${default}" ]]; then cur="${default}"; fi
  if [[ -f "${VALUES_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${VALUES_FILE}" 2>/dev/null || true
    eval "cur=\${${var}:-${cur}}"
  fi
  if [[ "${NONINTERACTIVE:-0}" == "1" ]]; then
    [[ -n "${cur}" ]] || die "Non-interactive: missing ${var}"
    printf -v "${var}" '%s' "${cur}"
    return
  fi
  if [[ "${secret}" == "1" ]]; then
    read -r -s -p "${label}: " input
    echo ""
  else
    if [[ -n "${cur}" ]]; then
      read -r -p "${label} [${cur}]: " input
    else
      read -r -p "${label}: " input
    fi
  fi
  if [[ -z "${input}" ]]; then
    input="${cur}"
  fi
  [[ -n "${input}" ]] || die "${label} is required"
  printf -v "${var}" '%s' "${input}"
}

validate_url() {
  [[ "$1" =~ ^https?:// ]] || die "Invalid URL: $1"
}

validate_password_strength() {
  local p="$1"
  [[ ${#p} -ge 16 ]] || die "Password/secret must be at least 16 characters"
  case "${p}" in
    CHANGE_ME|password|Password1|admin|secret|REPLACE*) die "Default/placeholder secrets are rejected" ;;
  esac
}

NONINTERACTIVE=0
if [[ "${1:-}" == "--from-example" ]] || [[ "${1:-}" == "--non-interactive" ]]; then
  NONINTERACTIVE=1
  if [[ ! -f "${VALUES_FILE}" ]]; then
    [[ -f "${EXAMPLE}" ]] || die "Missing ${EXAMPLE}"
    die "Copy ${EXAMPLE} to ${VALUES_FILE}, fill values, then re-run with --non-interactive"
  fi
fi

if [[ "${NONINTERACTIVE}" == "0" ]]; then
  echo "Interactive configuration. Secrets will not be echoed."
  echo "Tip: for automation, edit config/deployment-values.env and use --non-interactive"
fi

prompt_val IMAGE_SOURCE "Deployment image mode (offline|registry)" "offline"
prompt_val FRONTEND_PUBLIC_URL "Frontend public URL (https://...)" "https://survey-pilot.example.ae"
prompt_val BACKEND_PUBLIC_URL "Backend public URL (usually same as frontend)" "${FRONTEND_PUBLIC_URL:-https://survey-pilot.example.ae}"
prompt_val GPS_BACKEND_URL "GPS backend URL" "https://api-kodikz.giantphoenixllc.com"
prompt_val POSTGRES_DB "PostgreSQL database name" "giscd"
prompt_val POSTGRES_USER "PostgreSQL username" "kodikz"
prompt_val POSTGRES_PASSWORD "PostgreSQL password" "" 1
prompt_val MONGODB_URL "MongoDB URL (optional; leave empty if GPS-owned external)" "" 0
prompt_val S3_ENDPOINT "Object-storage endpoint" "http://minio:9000"
prompt_val S3_ACCESS_KEY_ID "Object-storage access key" "" 1
prompt_val S3_SECRET_ACCESS_KEY "Object-storage secret key" "" 1
prompt_val AUTH_JWT_SECRET "Authentication JWT secret" "" 1
prompt_val CORS_ORIGINS "Allowed CORS origins (comma-separated)" "${FRONTEND_PUBLIC_URL}"
prompt_val ADMIN_EMAIL "Initial administrator email" "admin@example.ae"
prompt_val TLS_MODE "TLS mode (external|terminate-nginx|http-only)" "terminate-nginx"
prompt_val TLS_CERT_DIR "Certificate directory (for terminate-nginx)" "${PKG_ROOT}/data/certs"
prompt_val BACKUP_RETENTION_DAYS "Backup retention days" "14"
prompt_val HTTP_PORT "HTTP port" "80"
prompt_val HTTPS_PORT "HTTPS port" "443"

validate_url "${FRONTEND_PUBLIC_URL}"
validate_url "${BACKEND_PUBLIC_URL}"
validate_url "${GPS_BACKEND_URL}"
validate_password_strength "${POSTGRES_PASSWORD}"
validate_password_strength "${S3_ACCESS_KEY_ID}"
validate_password_strength "${S3_SECRET_ACCESS_KEY}"
validate_password_strength "${AUTH_JWT_SECRET}"
[[ "${ADMIN_EMAIL}" == *"@"* ]] || die "Invalid ADMIN_EMAIL"
[[ "${BACKUP_RETENTION_DAYS}" =~ ^[0-9]+$ ]] || die "BACKUP_RETENTION_DAYS must be numeric"
case "${IMAGE_SOURCE}" in offline|registry) ;; *) die "IMAGE_SOURCE must be offline or registry" ;; esac
case "${TLS_MODE}" in external|terminate-nginx|http-only) ;; *) die "Invalid TLS_MODE" ;; esac

if [[ "${TLS_MODE}" == "terminate-nginx" ]]; then
  if [[ ! -f "${TLS_CERT_DIR}/fullchain.pem" ]] || [[ ! -f "${TLS_CERT_DIR}/privkey.pem" ]]; then
    echo "WARNING: TLS cert files not found yet under ${TLS_CERT_DIR} (fullchain.pem, privkey.pem)."
    echo "         Place them before deploy if using terminate-nginx."
  fi
fi

# Write values file (operator editable) — still 600
umask 077
{
  echo "# Generated by configure.sh — contains secrets. Mode 600."
  echo "IMAGE_SOURCE=${IMAGE_SOURCE}"
  echo "FRONTEND_PUBLIC_URL=${FRONTEND_PUBLIC_URL}"
  echo "BACKEND_PUBLIC_URL=${BACKEND_PUBLIC_URL}"
  echo "GPS_BACKEND_URL=${GPS_BACKEND_URL}"
  echo "POSTGRES_DB=${POSTGRES_DB}"
  echo "POSTGRES_USER=${POSTGRES_USER}"
  echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  echo "MONGODB_URL=${MONGODB_URL}"
  echo "S3_ENDPOINT=${S3_ENDPOINT}"
  echo "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}"
  echo "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}"
  echo "AUTH_JWT_SECRET=${AUTH_JWT_SECRET}"
  echo "CORS_ORIGINS=${CORS_ORIGINS}"
  echo "ADMIN_EMAIL=${ADMIN_EMAIL}"
  echo "TLS_MODE=${TLS_MODE}"
  echo "TLS_CERT_DIR=${TLS_CERT_DIR}"
  echo "BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}"
  echo "HTTP_PORT=${HTTP_PORT}"
  echo "HTTPS_PORT=${HTTPS_PORT}"
} >"${VALUES_FILE}"
chmod 600 "${VALUES_FILE}"

# Compose-ready .env.production
{
  echo "# Autogenerated — do not commit. Permissions 600."
  echo "DEPLOYMENT_MODE=pilot"
  echo "APP_URL=${FRONTEND_PUBLIC_URL}"
  echo "AUTH_PROVIDER=local"
  echo "AUTH_JWT_SECRET=${AUTH_JWT_SECRET}"
  echo "AUTH_COOKIE_SECURE=$([ "${TLS_MODE}" = "http-only" ] && echo false || echo true)"
  echo "MOCK_AUTH_ENABLED=false"
  echo "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
  echo "DATABASE_SSL=false"
  echo "DATABASE_POOL_MAX=20"
  echo "STORAGE_PROVIDER=s3"
  echo "S3_ENDPOINT=${S3_ENDPOINT}"
  echo "S3_REGION=me-central-1"
  echo "S3_BUCKET=kodikz-survey"
  echo "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}"
  echo "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}"
  echo "S3_FORCE_PATH_STYLE=true"
  echo "UPLOAD_MAX_BYTES=8388608"
  echo "REDIS_ENABLED=false"
  echo "WORKER_ENABLED=true"
  echo "WORKER_POLL_MS=2000"
  echo "NEXT_PUBLIC_API_URL=${GPS_BACKEND_URL}"
  echo "NEXT_PUBLIC_SOCKET_URL=${GPS_BACKEND_URL}"
  echo "GEOCODING_PROVIDER=nominatim"
  echo "LOG_LEVEL=info"
  echo "POSTGRES_USER=${POSTGRES_USER}"
  echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  echo "POSTGRES_DB=${POSTGRES_DB}"
  echo "CORS_ORIGINS=${CORS_ORIGINS}"
  echo "ADMIN_EMAIL=${ADMIN_EMAIL}"
  echo "IMAGE_SOURCE=${IMAGE_SOURCE}"
  echo "TLS_MODE=${TLS_MODE}"
  echo "TLS_CERT_DIR=${TLS_CERT_DIR}"
  echo "BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}"
  echo "HTTP_PORT=${HTTP_PORT}"
  echo "HTTPS_PORT=${HTTPS_PORT}"
  echo "APP_IMAGE=kodikz-smart-city-app:1.0.0-rc1"
  echo "WORKER_IMAGE=kodikz-smart-city-worker:1.0.0-rc1"
  echo "KODIKZ_GIT_COMMIT=${GIT_COMMIT}"
  echo "KODIKZ_BUILD_TIME=${BUILD_TIMESTAMP:-REQUIRES_DOCKER_BUILD_HOST}"
  echo "KODIKZ_IMAGE_DIGEST=${APP_IMAGE_DIGEST:-REQUIRES_DOCKER_BUILD_HOST}"
  echo "KODIKZ_MIGRATION_VERSION=${POSTGRES_SCHEMA_VERSION:-1}"
  echo "NEXT_PUBLIC_KODIKZ_GIT_COMMIT=${GIT_COMMIT}"
  echo "NEXT_PUBLIC_KODIKZ_BUILD_TIME=${BUILD_TIMESTAMP:-REQUIRES_DOCKER_BUILD_HOST}"
  echo "POSTGRES_DATA_DIR=${PKG_ROOT}/data/postgres"
  echo "MINIO_DATA_DIR=${PKG_ROOT}/data/minio"
  if [[ -n "${MONGODB_URL}" ]]; then
    echo "MONGODB_URL=${MONGODB_URL}"
  fi
} >"${ENV_FILE}"
chmod 600 "${ENV_FILE}"

audit "configure wrote env (secrets redacted in audit)"
echo "Configuration written to config/.env.production (mode 600)."
echo "Secrets were not printed."
next_action "Run ./scripts/validate-config.sh then ./scripts/deploy.sh"
